# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Code-Push-Server-Go

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"

      - name: Build Application
        run: |
          echo "Building the application..."
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o code-push-server-go main.go
          find $(pwd) -name code-push-server-go  # Kiểm tra xem binary được build ở đâu
          echo "Build completed successfully."

      - name: Restart Application
        run: |
          echo "Restarting the application..."
          cd $GITHUB_WORKSPACE  # Chuyển đến thư mục làm việc chính
          binary_path=$(find $(pwd) -name code-push-server-go | head -n 1)
          if [ -z "$binary_path" ]; then
            echo "Binary not found! Exiting..."
            exit 1
          fi
          pkill -f code-push-server-go || true  # Tắt ứng dụng cũ nếu có
          nohup "$binary_path" > app.log 2>&1 &
          sleep 2  # Chờ ứng dụng khởi động
          pgrep -f code-push-server-go || { echo "Application failed to start."; exit 1; }
          echo "Application restarted successfully."
